nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: https://github.com/AngelKyriako?tab=repositories

projects_url: https://github.com/AngelKyriako?tab=repositories

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/AngelKyriako?tab=repositories
        # twitter: /
        # facebook: /
        linkedin: https://linkedin.com/in/angelkyriako
        codepen: http://codepen.io/angelkyriako
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: angelkyriako # https://disqus.com/home/settings/account/
    google_analytics: UA-90696360-1 # https://analytics.google.com/analytics/web
    swifttype_id: -bxh8C92ZvwjPKSavSpz # https://app.swiftype.com/engines/angelkyriako-dot-github-dot-io/overview

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
